--MYSQL
CREATE TABLE Paciente (
    id_paciente INT PRIMARY KEY AUTO_INCREMENT,
    nombre VARCHAR(50) NOT NULL,
    apellido VARCHAR(50) NOT NULL,
    dni VARCHAR(15) UNIQUE NOT NULL,
    fecha_nacimiento DATE NOT NULL,
    sexo CHAR(1) CHECK (sexo IN ('M', 'F')) NOT NULL,
    telefono VARCHAR(20),
    direccion VARCHAR(200),
    email VARCHAR(100) UNIQUE NOT NULL,
    CONSTRAINT FOREIGN KEY(id_historial_medico) REFERENCES HISTORIAL_MEDICO(id_historial_medico)
);

CREATE TABLE Historial_Medico(
    id_historial_medico NUMBER(6) PRIMARY KEY,
    antecedentes_historial VARCHAR2(100),
    alergias_historial VARCHAR2(100),
    enfermedades_cronicas VARCHAR(100)
);

--ORACLE
CREATE TABLE Medico(
    ID_MEDICO NUMBER(6) PRIMARY KEY,
    NOMBRE VARCHAR2(50) NOT NULL,
    APELLIDO VARCHAR(50) NOT NULL,
    EMAIL VARCHAR2(100) UNIQUE NOT NULL,
    ESTADO CHAR(10) CHECK(ESTADO IN ('activo','inactivo')) NOT NULL
     
);

CREATE TABLE Cita(
    ID_CITA NUMBER(6) PRIMARY KEY,
    FECHA DATE NOT NULL,
    HORA VARCHAR(10) NOT NULL,
    ESTADO VARCHAR(20) CHECK (ESTADO IN ('disponible','ocupado','no_disponible')) NOT NULL,
    MOTIVO VARCHAR(255) NOT NULL,
    ID_MEDICO NUMBER(6) NOT NULL,
    ID_PACIENTE NUMBER(6) NOT NULL,
    CONSTRAINT FOREIGN KEY(ID_MEDICO) REFERENCES MEDICO(ID_MEDICO),
    CONSTRAINT FOREIGN KEY (ID_PACIENTE) REFERENCES PACIENTE(ID_PACIENTE)

);

CREATE TABLE EXAMEN_MEDICO(
    ID_EXAMEN NUMBER(6) PRIMARY KEY,
    TIPO_EXMEN VARCHAR2(20) CHECK (TIPO_EXMEN IN ('SANGRE','RAYOSX','ECOGRAFIA','ORINA')) NOT NULL, 
    FECHA_EXMEN DATE NOT NULL,
    RESULTADO_EXMEN VARCHAR(180) NOT NULL,
    ID_CITA NUMBER(6) NOT NULL,
    CONSTRAINT FOREIGN KEY (ID_CITA) REFERENCES Cita(ID_CITA)
);


--ORACLE
CREATE TABLE Medicamento(
    ID_MEDICAMENTO NUMBER(6) PRIMARY KEY,
    nombre_medcmnto VARCHAR2(100) NOT NULL,
    presentacion CHECK (presentacion IN ('CAPSULA','JARABE','INYECTABLE','MASTICABLE')),
    descrip_medcmnto VARCHAR(200)
);


CREATE TABLE Receta_Medicamento(
    id_receta_medicamento NUMBER(6) PRIMARY KEY,
    indicaciones_medcmnto VARCHAR2(255),    
    ID_MEDICAMENTO NUMBER(6) NOT NULL,
    CONSTRAINT FOREIGN KEY(id_medicamento) REFERENCES Medicamento(id_medicamento)
    
);

CREATE TABLE Receta(
    id_receta NUMBER(6) PRIMARY KEY,
    indicaciones_receta VARCHAR(255) NOT NULL,
    ID_CITA NUMBER(6) NOT NULL,
    CONSTRAINT FOREIGN KEY(ID_CITA) REFERENCES CITA(ID_CITA)
    
);

--ORACLE
CREATE TABLE Enfermedad(
    id_enfermedad NUMBER(6) PRIMARY KEY,
    nombre_ENFRMDAD VARCHAR2(100) NOT NULL,
    descrip_ENFRMDAD VARCHAR(255)
);


CREATE TABLE Tratamiento(
    id_tratamiento NUMBER(6) PRIMARY KEY,
    descrip_TRTMNTO VARCHAR(255),
    duracion_TRTMNTO NUMBER,
    id_diagnostico number(6) not null,
    CONSTRAINT FOREIGN KEY(id_diagnostico) REFERENCES DIAGNOSTICO(id_diagnostico)
);


CREATE TABLE Diagnostico(
    id_diagnostico NUMBER(6) PRIMARY KEY,
    descripcion_DGNSTICO VARCHAR(255),
    ID_ENFERMEDAD NUMBER(6) NOT NULL,
    ID_CITA NUMBER(6) NOT NULL,
    CONSTRAINT FOREIGN KEY(id_enfermedad) REFERENCES Enfermedad(id_enfermedad),
    CONSTRAINT FOREIGN KEY(id_CITA) REFERENCES Cita(id_cita)
);


--RodEds ESPECIALIDAD-ROL-TRATAMIENTO-DIAGNOSTICO

CREATE TABLE ESPECIALIDAD(
    ID_ESPECIALIDAD NUMBER(6) PRIMARY KEY,
    NOMBRE_ESPCLIDAD VARCHAR2(100) NOT NULL,
    DESCRIPCION_ESPCLIDAD VARCHAR(200)    
);

CREATE TABLE USUARIO_SISTEMA(
    ID_USUARIO NUMBER(6) PRIMARY KEY,
    NOMBRE_USER VARCHAR(50) NOT NULL,
    CONTRASEÑA_USER VARCHAR(100),
    EMAIL_USER VARCHAR(100) UNIQUE,
    ID_ROL NUMBER(6) NOT NULL,
    CONSTRAINT FOREIGN KEY(ID_ROL) REFERENCES ROL(ID_ROL)

);

CREATE TABLE FACTURA (
    ID_FACTURA NUMBER(6) PRIMARY KEY,
    MONTO_TOTAL NUMBER(6) NOT NULL,
    ESTADO CHAR(25) CHECK (ESTADO IN ('CANCELADO', 'PAGADO', 'PENDIENTE')),
    METODO_FACTURACION VARCHAR2(100),
    ID_USUARIO NUMBER(6) NOT NULL,
    ID_PACIENTE NUMBER(6) NOT NULL,
    CONSTRAINT fk_factura_usuario FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO_SISTEMA(ID_USUARIO),
    CONSTRAINT fk_factura_paciente FOREIGN KEY (ID_PACIENTE) REFERENCES PACIENTE(ID_PACIENTE)
);


CREATE TABLE PAGO(
    ID_PAGO NUMBER(6) PRIMARY KEY,
    MONTO NUMBER(6) NOT NULL,
    METODO_PAGO CHAR(25) CHECK(METODO_PAGO IN ('EFECTIVO','TARJETA')) NOT NULL,
    FECHA_PAGO DATE NOT NULL,
    ID_CITA NUMBER(6) NOT NULL,
    CONSTRAINT FOREIGN KEY(ID_CITA) REFERENCES Cita(ID_CITA)
);

CREATE TABLE ROL(
    ID_ROL NUMBER(6) PRIMARY KEY,
    NOMBRE_ROL CHAR(25) CHECK(NOMBRE_ROL IN ('PACIENTE','MEDICO','ADMIN')) NOT NULL
);

CREATE TABLE TURNO_MEDICO(
    ID_TURNO NUMBER(6) PRIMARY KEY,
    DIA_SEMANA VARCHAR(20) NOT NULL,
    HORA_INICIO VARCHAR(10) NOT NULL,
    HORA_FIN VARCHAR(10) NOT NULL,
    ID_MEDICO NUMBER(6) NOT NULL,
    CONSTRAINT FOREIGN KEY(ID_MEDICO) REFERENCES MEDICO(ID_MEDICO)
);

CREATE TABLE Sala(
    ID_SALA NUMBER(6) PRIMARY KEY,
    NOMBRE VARCHAR(50) NOT NULL,
    TIPO VARCHAR(50),
    ESTADO VARCHAR(20) CHECK (ESTADO IN ('disponible','ocupado','no-disponible')) NOT NULL
);


--RodEds CON CONSTRAINS

